apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route-{{PROJECT_ID}}
  namespace: {{K8S_NAMESPACE}}
  labels:
    slipstream.io/project: {{PROJECT_ID}}
spec:
  parentRefs:
    - name: {{GATEWAY_NAME}}
      namespace: {{GATEWAY_NAMESPACE}}
  hostnames:
    - "{{GATEWAY_HOSTNAME}}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /env/{{NAMESPACE_SLUG}}/{{PROJECT_SLUG}}
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: svc-{{PROJECT_ID}}
          namespace: {{K8S_NAMESPACE}}
          port: 8080
