apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{PVC_NAME}}
  namespace: {{K8S_NAMESPACE}}
  labels:
    slipstream.io/project: {{PROJECT_ID}}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{STORAGE_CLASS}}
  resources:
    requests:
      storage: 10Gi
