apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    {{- include "slipstream.labels" . | nindent 4 }}
{{- if .Values.victoriametrics.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.victoriametrics.namespace }}
  labels:
    {{- include "slipstream.labels" . | nindent 4 }}
{{- end }}
