{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slipstream-postgres-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slipstream.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.postgresql.storageClass }}
  resources:
    requests:
      storage: {{ .Values.postgresql.storage }}
{{- end }}
