apiVersion: v1
kind: ConfigMap
metadata:
  name: slipstream-web-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slipstream.labels" . | nindent 4 }}
data:
  APP_URL: {{ include "slipstream.appUrl" . | quote }}
  ORIGIN: {{ include "slipstream.appUrl" . | quote }}
  WEB_NAMESPACE: {{ .Release.Namespace | quote }}
  {{- if .Values.devMode.enabled }}
  DEV_MODE: "true"
  {{- end }}
  {{- if .Values.registry.enabled }}
  HARBOR_URL: {{ .Values.registry.harborUrl | quote }}
  HARBOR_ADMIN_USERNAME: {{ .Values.registry.adminUsername | quote }}
  REGISTRY_HOST: {{ .Values.registry.host | quote }}
  {{- if .Values.registry.hostname }}
  REGISTRY_HOSTNAME: {{ .Values.registry.hostname | quote }}
  {{- end }}
  {{- end }}
