apiVersion: v1
kind: Service
metadata:
  name: slipstream-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slipstream.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "slipstream.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
    {{- if .Values.certManager.enabled }}
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
    {{- end }}
